<?php
use Illuminate\Database\Seeder;
class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('allergies')->insert([
            [
                'allergy_id' => '1',
                'parent_id' => '0',
                'allergy_name' => 'Pollens',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '2',
                'parent_id' => '1',
                'allergy_name' => 'Accasia arabica',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '3',
                'parent_id' => '1',
                'allergy_name' => 'Amaranthus-spinousus',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '4',
                'parent_id' => '1',
                'allergy_name' => 'Argemone mexicana',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '5',
                'parent_id' => '1',
                'allergy_name' => 'Artimisia scoparia',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '6',
                'parent_id' => '1',
                'allergy_name' => 'Brassica campestris',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '7',
                'parent_id' => '1',
                'allergy_name' => 'Broussonetia papyrifera',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '8',
                'parent_id' => '1',
                'allergy_name' => 'Cannabis saliva',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '9',
                'parent_id' => '1',
                'allergy_name' => 'Carica papaya',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '10',
                'parent_id' => '1',
                'allergy_name' => 'Cassia occidentalis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '11',
                'parent_id' => '1',
                'allergy_name' => 'Cassia siarnea',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '12',
                'parent_id' => '1',
                'allergy_name' => 'Chenopodium album',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '13',
                'parent_id' => '1',
                'allergy_name' => 'Cocos nucifera',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '14',
                'parent_id' => '1',
                'allergy_name' => 'Cynodon dactylon',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '15',
                'parent_id' => '1',
                'allergy_name' => 'Holoptelia Intergrifolia',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '16',
                'parent_id' => '1',
                'allergy_name' => 'ipormea fistulosa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '17',
                'parent_id' => '1',
                'allergy_name' => 'Imperata cylindrica',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '18',
                'parent_id' => '1',
                'allergy_name' => 'MOMS alba',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '19',
                'parent_id' => '1',
                'allergy_name' => 'Partheniurn hysterophorus',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '20',
                'parent_id' => '1',
                'allergy_name' => 'Pennisetum typhoides',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '21',
                'parent_id' => '1',
                'allergy_name' => 'Prose* Juliffora',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '22',
                'parent_id' => '1',
                'allergy_name' => 'Ricinus Communis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '23',
                'parent_id' => '1',
                'allergy_name' => 'Xanthium strumarium',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '24',
                'parent_id' => '1',
                'allergy_name' => 'Dodonea viscosa',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '25',
                'parent_id' => '1',
                'allergy_name' => 'Eucalyptus tereticornis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '26',
                'parent_id' => '1',
                'allergy_name' => 'Azadirecta indica',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '27',
                'parent_id' => '1',
                'allergy_name' => 'Sorghum vulgare',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '28',
                'parent_id' => '1',
                'allergy_name' => 'Zea Mays',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '29',
                'parent_id' => '0',
                'allergy_name' => 'Fungus',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '30',
                'parent_id' => '29',
                'allergy_name' => 'Altemaria tennis',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '31',
                'parent_id' => '29',
                'allergy_name' => 'Aspergillus Flavus',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '32',
                'parent_id' => '29',
                'allergy_name' => 'Aspergillus Fumigatas',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '33',
                'parent_id' => '29',
                'allergy_name' => 'Aspergillus niger',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '34',
                'parent_id' => '29',
                'allergy_name' => 'Aspergillus tamarii',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '35',
                'parent_id' => '29',
                'allergy_name' => 'Candida albicans',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '36',
                'parent_id' => '29',
                'allergy_name' => 'Cladosporium herbarum',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '37',
                'parent_id' => '29',
                'allergy_name' => 'Curvularia lunata',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '38',
                'parent_id' => '29',
                'allergy_name' => 'Fusarium solani',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '39',
                'parent_id' => '29',
                'allergy_name' => 'Mucor mucedo',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '40',
                'parent_id' => '29',
                'allergy_name' => 'Neurospora sitophilla',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '41',
                'parent_id' => '29',
                'allergy_name' => 'Penicileum sp',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '42',
                'parent_id' => '29',
                'allergy_name' => 'Phomabatae',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '43',
                'parent_id' => '29',
                'allergy_name' => 'Rhizopus nigricans',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '44',
                'parent_id' => '29',
                'allergy_name' => 'Trichoderma sp',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '45',
                'parent_id' => '0',
                'allergy_name' => 'Insects',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '46',
                'parent_id' => '45',
                'allergy_name' => 'House dust mite D. Farinae',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '47',
                'parent_id' => '45',
                'allergy_name' => 'House dust mite D. Pteronyssinus',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '48',
                'parent_id' => '45',
                'allergy_name' => 'Ants',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '49',
                'parent_id' => '45',
                'allergy_name' => 'Cockroach female',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '50',
                'parent_id' => '45',
                'allergy_name' => 'Cockroach male',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '51',
                'parent_id' => '45',
                'allergy_name' => 'Cricket',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '52',
                'parent_id' => '45',
                'allergy_name' => 'Grasshopper',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '53',
                'parent_id' => '45',
                'allergy_name' => 'House Fly',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '54',
                'parent_id' => '45',
                'allergy_name' => 'Honey bee',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '55',
                'parent_id' => '45',
                'allergy_name' => 'Mosquitoes',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '56',
                'parent_id' => '45',
                'allergy_name' => 'Moth',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '57',
                'parent_id' => '45',
                'allergy_name' => 'Rice weevil',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '58',
                'parent_id' => '45',
                'allergy_name' => 'Yellow wasp',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '59',
                'parent_id' => '0',
                'allergy_name' => 'Dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '60',
                'parent_id' => '59',
                'allergy_name' => 'Cotton dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '61',
                'parent_id' => '59',
                'allergy_name' => 'Hay dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '62',
                'parent_id' => '59',
                'allergy_name' => 'House dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '63',
                'parent_id' => '59',
                'allergy_name' => 'Paper dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '64',
                'parent_id' => '59',
                'allergy_name' => 'Wheat grain dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '65',
                'parent_id' => '59',
                'allergy_name' => 'Rice grain dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '66',
                'parent_id' => '59',
                'allergy_name' => 'Wheat threshing dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '67',
                'parent_id' => '59',
                'allergy_name' => 'Soyabean dust',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '68',
                'parent_id' => '0',
                'allergy_name' => 'Danders',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '69',
                'parent_id' => '68',
                'allergy_name' => 'Buffalo dander',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '70',
                'parent_id' => '68',
                'allergy_name' => 'Cow dander',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '71',
                'parent_id' => '68',
                'allergy_name' => 'Cat dander',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '72',
                'parent_id' => '68',
                'allergy_name' => 'Dog epithelium',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '73',
                'parent_id' => '68',
                'allergy_name' => 'Human dander',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '74',
                'parent_id' => '68',
                'allergy_name' => 'Horse dander',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '75',
                'parent_id' => '0',
                'allergy_name' => 'Fabrics & feathers',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '76',
                'parent_id' => '75',
                'allergy_name' => 'Chicken feather',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '77',
                'parent_id' => '75',
                'allergy_name' => 'Pigeon feather',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '78',
                'parent_id' => '75',
                'allergy_name' => 'Kappok Cotton',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '79',
                'parent_id' => '75',
                'allergy_name' => 'Wool mixed',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '80',
                'parent_id' => '75',
                'allergy_name' => 'Skill raw',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '81',
                'parent_id' => '0',
                'allergy_name' => 'Foods',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '82',
                'parent_id' => '81',
                'allergy_name' => 'Bengal gram',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '83',
                'parent_id' => '81',
                'allergy_name' => 'Dal arhar',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '84',
                'parent_id' => '81',
                'allergy_name' => 'Dal urd',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '85',
                'parent_id' => '81',
                'allergy_name' => 'Dal moong',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '86',
                'parent_id' => '81',
                'allergy_name' => 'Dal masoor',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '87',
                'parent_id' => '81',
                'allergy_name' => 'Kabuli chana',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '88',
                'parent_id' => '81',
                'allergy_name' => 'Rajma',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '89',
                'parent_id' => '81',
                'allergy_name' => 'Ground nut',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '90',
                'parent_id' => '81',
                'allergy_name' => 'Mustard',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '91',
                'parent_id' => '81',
                'allergy_name' => 'Soyabean',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '92',
                'parent_id' => '81',
                'allergy_name' => 'Coconut',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '93',
                'parent_id' => '81',
                'allergy_name' => 'Almond',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '94',
                'parent_id' => '81',
                'allergy_name' => 'Cashew nut',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '95',
                'parent_id' => '81',
                'allergy_name' => 'Milk & Milk Products',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '96',
                'parent_id' => '81',
                'allergy_name' => 'Curd',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '97',
                'parent_id' => '81',
                'allergy_name' => 'Tea',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '98',
                'parent_id' => '81',
                'allergy_name' => 'Coffee bean',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '99',
                'parent_id' => '81',
                'allergy_name' => 'Chocolate',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '100',
                'parent_id' => '81',
                'allergy_name' => 'Wheat',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '101',
                'parent_id' => '81',
                'allergy_name' => 'Rice',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '102',
                'parent_id' => '81',
                'allergy_name' => 'Maize',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '103',
                'parent_id' => '81',
                'allergy_name' => 'Jowar',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '104',
                'parent_id' => '81',
                'allergy_name' => 'Bajra',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '105',
                'parent_id' => '81',
                'allergy_name' => 'Barley',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '106',
                'parent_id' => '81',
                'allergy_name' => 'Sago',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '107',
                'parent_id' => '81',
                'allergy_name' => 'Yeast',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '108',
                'parent_id' => '81',
                'allergy_name' => 'Onion',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '109',
                'parent_id' => '81',
                'allergy_name' => 'Garlic',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '110',
                'parent_id' => '81',
                'allergy_name' => 'Ginger',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '111',
                'parent_id' => '81',
                'allergy_name' => 'Tomato',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '112',
                'parent_id' => '81',
                'allergy_name' => 'Lemon',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '113',
                'parent_id' => '81',
                'allergy_name' => 'Potato',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '114',
                'parent_id' => '81',
                'allergy_name' => 'Cabbage',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '115',
                'parent_id' => '81',
                'allergy_name' => 'Cauliflower',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '116',
                'parent_id' => '81',
                'allergy_name' => 'Brinjal',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '117',
                'parent_id' => '81',
                'allergy_name' => 'Spinach',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '118',
                'parent_id' => '81',
                'allergy_name' => 'Peas',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '119',
                'parent_id' => '81',
                'allergy_name' => 'Bean',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '120',
                'parent_id' => '81',
                'allergy_name' => 'Cucumber',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '121',
                'parent_id' => '81',
                'allergy_name' => 'Egg',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '122',
                'parent_id' => '81',
                'allergy_name' => 'Fish',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '123',
                'parent_id' => '81',
                'allergy_name' => 'Mutton',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '124',
                'parent_id' => '81',
                'allergy_name' => 'Chicken',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '125',
                'parent_id' => '81',
                'allergy_name' => 'Prawn',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '126',
                'parent_id' => '81',
                'allergy_name' => 'Apple',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '127',
                'parent_id' => '81',
                'allergy_name' => 'Banana',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '128',
                'parent_id' => '81',
                'allergy_name' => 'Mango',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '129',
                'parent_id' => '81',
                'allergy_name' => 'Orange',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '130',
                'parent_id' => '81',
                'allergy_name' => 'Papaya',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '131',
                'parent_id' => '81',
                'allergy_name' => 'Pineapple',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '132',
                'parent_id' => '81',
                'allergy_name' => 'Grape',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '133',
                'parent_id' => '81',
                'allergy_name' => 'Pear',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '134',
                'parent_id' => '81',
                'allergy_name' => 'Cherry',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '135',
                'parent_id' => '81',
                'allergy_name' => 'Pumpkin',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '136',
                'parent_id' => '81',
                'allergy_name' => 'Wall nut',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '137',
                'parent_id' => '81',
                'allergy_name' => 'Sonf',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '138',
                'parent_id' => '81',
                'allergy_name' => 'Sonth',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '139',
                'parent_id' => '81',
                'allergy_name' => 'Chilli Powder',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '140',
                'parent_id' => '81',
                'allergy_name' => 'Turmeric',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '141',
                'parent_id' => '81',
                'allergy_name' => 'Black pepper',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '142',
                'parent_id' => '81',
                'allergy_name' => 'Cinnamon',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '143',
                'parent_id' => '81',
                'allergy_name' => 'Clave',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '144',
                'parent_id' => '81',
                'allergy_name' => 'Tamarind',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '145',
                'parent_id' => '81',
                'allergy_name' => 'Gum acacia',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '146',
                'parent_id' => '81',
                'allergy_name' => 'Radish',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '147',
                'parent_id' => '81',
                'allergy_name' => 'Carrot',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '148',
                'parent_id' => '81',
                'allergy_name' => 'Mushroom',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '149',
                'parent_id' => '0',
                'allergy_name' => 'Miscellaneous',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '150',
                'parent_id' => '149',
                'allergy_name' => 'Tobacco',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '151',
                'parent_id' => '149',
                'allergy_name' => 'Brewers Yeast',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '152',
                'parent_id' => '149',
                'allergy_name' => 'Parithenium leaves',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '153',
                'parent_id' => '149',
                'allergy_name' => 'Piymix wood',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '154',
                'parent_id' => '149',
                'allergy_name' => 'Saal wood',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
            [
                'allergy_id' => '155',
                'parent_id' => '149',
                'allergy_name' => 'Teak wood',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'resource_type' => '1',
                'ip_address' => '',
                'created_by' => 0,
                'updated_by' => 0,
            ],
        ]);

    }
}
