<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePaymentHistoryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        if (!Schema::hasTable('payments_history')) {
            Schema::create('payments_history', function (Blueprint $table) {
                $table->increments('payment_id')->comment('Primary Key of payment history table');
                $table->string('reciept_number','100')->nullable()->comment('Autogenerated reciept number');
                $table->integer('user_id')->unsigned()->comment('Foreign key of doctor from users table ( user_id )');
                $table->integer('pat_id')->unsigned()->comment('Foreign key of patient from users table ( user_id )');
                $table->decimal('amount')->comment('Amount given for the visit');
                $table->integer('checkup_type_id')->unsigned()->nullable()->comment('Payment given for Foriegn key from checkup type table');
                $table->integer('payment_mode_id')->unsigned()->nullable()->comment('Payment mode if Foriegn key from payment mode table');
                $table->tinyInteger('resource_type')->unsigned()->nullable()->comment('Resource type - 1 For Web  , 2 for Android and 3 for IOS');
                $table->string('ip_address',50)->nullable()->comment('User last login ip');
                $table->integer('created_by')->unsigned()->nullable()->default(0)->comment('0 for self/by system');
                $table->integer('updated_by')->unsigned()->nullable()->default(0)->comment('0 for self/by system');
                $table->tinyInteger('is_deleted')->unsigned()->nullable()->default(2)->comment('1 for deleted yes and 2 for deleted no');
                $table->timestamps();
            });
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('payment_history');
    }
}
