<?php
/**
 *@ShortDescription Define all constants that going to use in the Application.
 *
 * @var Array
 */
return [
    'SPIROMETRY_FEV1_FACTOR_ID'             => '1',
    'SPIROMETRY_FVC_FACTOR_ID'              => '2',
    'SPIROMETRY_FEV1_FVC_FACTOR_ID'         => '3',
    'SPIROMETRY_PEFFR_FACTOR_ID'            => '4',
    'SPIROMETRY_LUNG_CAPACITY_FACTOR_ID'    => '5',
    'SPIROMETRY_RESIDUAL_VOLUME_FACTOR_ID'  => '6',
    'SPIROMETRY_DLCO_FACTOR_ID'             => '7',
    'SPIROMETRY_ML_MMHG_FACTOR_ID'          => '8',
    'SPIROMETRY_ML_KPG_FACTOR_ID'           => '9',
    'SPIROMETRY_KCO_FACTOR_ID'              => '10',
    'MEDICINE_DURATION_UNIT_DAYS'           => 1,
    'MEDICINE_DURATION_UNIT_WEEKS'          => 2,
    'MEDICINE_DURATION_UNIT_MONTHS'         => 3,
    'MEDICINE_DURATION_UNIT_YEARS'          => 4,
    'VISIT_STATUS_IN_PROGRESS'              => 1,
    'VISIT_STATUS_FINISHED'                 => 2,
    'VISIT_STATUS_CANCEL'                   => 3,
    'CHEST_XRAY_RECENT_TYPE'                => 1,
    'CHEST_XRAY_OLD_TYPE'                   => 2,
    'DISEASE_FOUNT_NEVER'                   => 1,
    'DISEASE_FOUNT_BEFORE_ILD_TREATMENT'    => 2,
    'DISEASE_FOUNT_AFTER_ILD_TREATMENT'     => 3,
    'VISIT_VITALS_WEIGHT'                   => 1,
    'VISIT_VITALS_PULSE'                    => 2,
    'VISIT_VITALS_BP_SYS'                   => 3,
    'VISIT_VITALS_BP_DIA'                   => 4,
    'VISIT_VITALS_SPO2'                     => 5,
    'VISIT_VITALS_RESPIRATORY_RATE'         => 6,
    'VISIT_VITALS_TEMPERATURE'              => 7,
    'VISIT_VITALS_SUGARLEVEL'               => 8,
    'VISIT_VITALS_JVP'                      => 9,
    'VISIT_VITALS_PEDELEDEMA'               => 10,
    'VISIT_PHYSICAL_EXAMINATION_BMI'        => 3,
    'VISIT_PHYSICAL_WEIGHT'                 => 1,
    'FIRST_FOLLOWUP_VISIT_NUMBER'           => 2,
    'MARITAL_STATUS_MARRIED'                => 1,
    'MARITAL_STATUS_UNMARRIED'              => 2,
    'DISEASE_STATUS_ACTIVE'                 => 1,
    'DISEASE_STATUS_INACTIVE'               => 2,
    'FILE_TYPE_INVESTIGATION_REPORT'        => 'investigation-report',
    'ALLERGIES_STATUS_ACTIVE'               => 1,
    'ALLERGIES_STATUS_INACTIVE'             => 2,
    'DEFAULT_PAYMENT_MODE_ID'               => 0,
    'DEFAULT_CHECKUP_TYPE_ID'               => 0,
    'PARENT_ALLERGY_PARENT_ID'              => 0,
];